# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='test.proto',
  package='lth.egmTest',
  serialized_pb='\n\ntest.proto\x12\x0blth.egmTest\"\x18\n\x06Header\x12\x0e\n\x06sender\x18\x01 \x02(\x05\"\x13\n\x04\x42ody\x12\x0b\n\x03msg\x18\x01 \x02(\t\"N\n\x06Packet\x12#\n\x06header\x18\x01 \x02(\x0b\x32\x13.lth.egmTest.Header\x12\x1f\n\x04\x62ody\x18\x02 \x02(\x0b\x32\x11.lth.egmTest.Body')




_HEADER = descriptor.Descriptor(
  name='Header',
  full_name='lth.egmTest.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sender', full_name='lth.egmTest.Header.sender', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=51,
)


_BODY = descriptor.Descriptor(
  name='Body',
  full_name='lth.egmTest.Body',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='msg', full_name='lth.egmTest.Body.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=53,
  serialized_end=72,
)


_PACKET = descriptor.Descriptor(
  name='Packet',
  full_name='lth.egmTest.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='header', full_name='lth.egmTest.Packet.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='body', full_name='lth.egmTest.Packet.body', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=74,
  serialized_end=152,
)

_PACKET.fields_by_name['header'].message_type = _HEADER
_PACKET.fields_by_name['body'].message_type = _BODY
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Body'] = _BODY
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET

class Header(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEADER
  
  # @@protoc_insertion_point(class_scope:lth.egmTest.Header)

class Body(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BODY
  
  # @@protoc_insertion_point(class_scope:lth.egmTest.Body)

class Packet(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PACKET
  
  # @@protoc_insertion_point(class_scope:lth.egmTest.Packet)

# @@protoc_insertion_point(module_scope)
